version: '3.4'

services:
  pg:
    image: postgres
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Qwerty1
    command: postgres
  pg-docker:
    image: ${DOCKER_REGISTRY-}pgdocker
    build:
      context: .
      dockerfile: pg-docker/Dockerfile
